version: '2.0'

services:

  mysql:
    image: mysql
    #build:
    #  context: .
    #  dockerfile: docker-mysql
    restart: always
    networks:
      - dv-net
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
      - ./config/mysql.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

#  nginx:
#    image: nginx
#    restart: always
#    volumes:
#      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 81:80
#    links:
#      - covid_dv

  covid_dv:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - :/
    networks:
      - dv-net

      #  ipv4_address: 172.20.0.2
    ports:
      - 8001:8001
    expose:
      - 8001
    links:
      - mysql

networks:
  dv-net:
    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.20.0.0/16
#          #gateway: 172.20.0.1
