version: '2.0'

services:

  mysql:
    # image: mysql
    build:
      context: .
      dockerfile: docker-mysql
    restart: always
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      # - ./data/:/docker-entrypoint-initdb.d/
      - ./config/mysql.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 'root'

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links:
      - covid_dv

  covid_dv:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - .:/code
    expose:
      - 8001
    links:
      - mysql